# Generated by Django 5.0.2 on 2025-09-01 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='additional_technicians',
            field=models.ManyToManyField(blank=True, help_text='Additional technicians assigned to this ticket', related_name='additional_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='First technician who claimed this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('claimed', 'Claimed'), ('assigned', 'Assigned'), ('technician_added', 'Technician Added'), ('status_changed', 'Status Changed'), ('state_changed', 'State Changed'), ('closed', 'Closed'), ('attachment_added', 'Attachment Added'), ('message_sent', 'Message Sent')], max_length=20),
        ),
    ]
