# Generated by Django 5.0.2 on 2025-09-02 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_additional_technicians_ticket_claimed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['state'], name='tickets_tic_state_eeb4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='tickets_tic_priorit_0bec9b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['type'], name='tickets_tic_type_29dfeb_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['requester'], name='tickets_tic_request_d7d4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to'], name='tickets_tic_assigne_bcac0e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['claimed_by'], name='tickets_tic_claimed_4c1514_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['updated_at'], name='tickets_tic_updated_c8331d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['closed_at'], name='tickets_tic_closed__06327b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='tickets_tic_status_b256f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['state', 'created_at'], name='tickets_tic_state_ec6cea_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='tickets_tic_assigne_e36302_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['ticket'], name='tickets_tic_ticket__67c8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['uploaded_by'], name='tickets_tic_uploade_8c0e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_27ea20_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketevent',
            index=models.Index(fields=['ticket'], name='tickets_tic_ticket__fc31ab_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketevent',
            index=models.Index(fields=['actor'], name='tickets_tic_actor_i_6b8abf_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketevent',
            index=models.Index(fields=['event_type'], name='tickets_tic_event_t_2ddb35_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketevent',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_6b6f75_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketevent',
            index=models.Index(fields=['ticket', 'created_at'], name='tickets_tic_ticket__766ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket'], name='tickets_tic_ticket__0357e9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['sender'], name='tickets_tic_sender__fd3f53_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_f6dbd3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='tickets_tic_ticket__edb166_idx'),
        ),
    ]
