# Generated by Django 5.0.2 on 2025-09-06 03:50

import django.db.models.deletion
import tickets.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_tickets_tic_status_0e5646_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('claimed', 'Claimed'), ('assigned', 'Assigned'), ('technician_added', 'Technician Added'), ('status_changed', 'Status Changed'), ('state_changed', 'State Changed'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('attachment_added', 'Attachment Added'), ('message_sent', 'Message Sent')], max_length=20),
        ),
        migrations.CreateModel(
            name='TicketClosureReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_type', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('network', 'Network'), ('other', 'Autre')], max_length=20)),
                ('root_cause', models.TextField(help_text='Cause principale du problème')),
                ('solution_applied', models.TextField(help_text='Solution appliquée')),
                ('resolution_time_hours', models.PositiveIntegerField(default=0)),
                ('resolution_time_minutes', models.PositiveIntegerField(default=0)),
                ('parts_used', models.TextField(blank=True, help_text='Pièces ou logiciels utilisés')),
                ('technical_notes', models.TextField(blank=True, help_text='Notes techniques importantes')),
                ('recommendations', models.TextField(blank=True, help_text='Recommandations pour éviter le problème')),
                ('is_recurring_problem', models.BooleanField(default=False, help_text='Problème récurrent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_reports', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure_report', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketClosureReportAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('storage_url', models.FileField(upload_to=tickets.models.closure_report_attachment_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closure_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticketclosurereport')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='ticketclosurereport',
            index=models.Index(fields=['ticket'], name='tickets_tic_ticket__489237_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketclosurereport',
            index=models.Index(fields=['created_by'], name='tickets_tic_created_0fa319_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketclosurereport',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_3504a5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketclosurereport',
            index=models.Index(fields=['problem_type'], name='tickets_tic_problem_51e17b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketclosurereport',
            index=models.Index(fields=['is_recurring_problem'], name='tickets_tic_is_recu_94b668_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketclosurereportattachment',
            index=models.Index(fields=['closure_report'], name='tickets_tic_closure_f018d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketclosurereportattachment',
            index=models.Index(fields=['uploaded_by'], name='tickets_tic_uploade_a5e806_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketclosurereportattachment',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_8c9c65_idx'),
        ),
    ]
