# Generated by Django 5.0.2 on 2025-09-06 04:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticketevent_event_type_ticketclosurereport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketclosurereport',
            name='resolution_time_hours',
        ),
        migrations.RemoveField(
            model_name='ticketclosurereport',
            name='resolution_time_minutes',
        ),
        migrations.AddField(
            model_name='ticketclosurereport',
            name='problem_subtype',
            field=models.CharField(default='Non spécifié', help_text='Sous-type spécifique du problème', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReplacedPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_name', models.CharField(help_text='Nom de la pièce remplacée', max_length=200)),
                ('serial_number', models.CharField(blank=True, help_text='Numéro de série de la pièce', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closure_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_parts', to='tickets.ticketclosurereport')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['closure_report'], name='tickets_rep_closure_6b1ec8_idx'), models.Index(fields=['part_name'], name='tickets_rep_part_na_17d7c6_idx')],
            },
        ),
    ]
