# Generated by Django 5.0.2 on 2025-09-06 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticketclosurereport_resolution_time_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(help_text='Description du problème (peut contenir du HTML)'),
        ),
        migrations.AlterField(
            model_name='ticketclosurereport',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_reports', to='tickets.ticket'),
        ),
    ]
