# Generated by Django 5.0.2 on 2025-09-06 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_state_eeb4d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_state_ec6cea_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='state',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed'), ('Reopened', 'Reopened')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('claimed', 'Claimed'), ('assigned', 'Assigned'), ('technician_added', 'Technician Added'), ('status_changed', 'Status Changed'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('attachment_added', 'Attachment Added'), ('message_sent', 'Message Sent')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'created_at'], name='tickets_tic_status_8acd21_idx'),
        ),
    ]
