# Generated by Django 5.0.2 on 2025-09-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_user_users_user_email_6f2530_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logout',
            field=models.DateTimeField(blank=True, help_text='Last logout timestamp', null=True),
        ),
    ]
